name: Cloudbase-Init tests

env:
  UPPER_CONSTRAINTS: "upper-constraints.txt"
  TEST_RESOURCES: "https://github.com/cloudbase/cloudbase-init-test-resources"
  TEST_RESOURCES_BRANCH: "master"

on: [push, pull_request]

jobs:
  linux-unit-tests:
    runs-on: lxd_scale_set
    strategy:
      fail-fast: false

    steps:
    - name: Set up Python
      uses: actions/setup-python@v4
    - name: Install python3 tox
      shell: bash
      run: |
        python3 -m pip install tox setuptools --upgrade
