name: Cloudbase-Init tests

env:
  UPPER_CONSTRAINTS: "upper-constraints.txt"
  TEST_RESOURCES: "https://github.com/cloudbase/cloudbase-init-test-resources"
  TEST_RESOURCES_BRANCH: "master"

on: [push, pull_request]

jobs:
  linux-unit-tests:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false

    steps:
    - name: Checkout cloudbase-init repository
      uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.architecture }}
    - name: Install python3 tox
      shell: bash
      run: |
        python3 -m pip install tox setuptools --upgrade
    - name: Run Cloudbase-Init unit tests with tox
      shell: bash
      run: |
        tox run-parallel --parallel-live --parallel-no-spinner -e py3,pep8,cover,docs
